### PR TITLE
test/cjdns: update path to cexec script

### PR DESCRIPTION
**Pull request by kyrias**

### CODE REVIEW

**Comment by kyrias** [comment]
Though it seems like this doesn't fix the tests anyway..

```
1436727843 DEBUG Configurator.c:630 Cjdns started in the background
Traceback (most recent call last):
  File "contrib/python/cjdnsadminmaker.py", line 38, in <module>
    cjdnsadmin_path = sys.argv[1]
IndexError: list index out of range

/home/travis/build/thefinn93/cjdnsadmin/cjdns/contrib/nodejs/cjdnsadmin/cjdnsadmin.js:212
            if (err) { throw err; }
                             ^
Error: ENOENT, open '/home/travis/.cjdnsadmin'
```

**Comment by thefinn93** [comment]
Damn, i'll fuck with the travis shit in a bit. in the mean time, sure this looks fine. Merging.

**Comment by thefinn93** [comment]
Thanks for contribooting, I'd love more PRs if you feel so inclined... no specific TODOs but I'm sure there's plenty to clean up

**Comment by kyrias** [comment]
Yeah, I was planning on playing with the API some when I have time, at which time I'll send PRs for everything I can think of. :smile:

**Pull request merged**
